# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match.pb

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='match.pb',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08match.pb\";\n\x04Hero\x12\x0c\n\x04hero\x18\x01 \x01(\r\x12\x11\n\x05items\x18\x02 \x03(\rB\x02\x10\x01\x12\x12\n\ngold_spent\x18\x03 \x01(\r\"F\n\tMatchInfo\x12\x1d\n\x0eradiant_heroes\x18\x01 \x03(\x0b\x32\x05.Hero\x12\x1a\n\x0b\x64ire_heroes\x18\x02 \x03(\x0b\x32\x05.Herob\x06proto3')
)




_HERO = _descriptor.Descriptor(
  name='Hero',
  full_name='Hero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero', full_name='Hero.hero', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='Hero.items', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gold_spent', full_name='Hero.gold_spent', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=71,
)


_MATCHINFO = _descriptor.Descriptor(
  name='MatchInfo',
  full_name='MatchInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radiant_heroes', full_name='MatchInfo.radiant_heroes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dire_heroes', full_name='MatchInfo.dire_heroes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=143,
)

_MATCHINFO.fields_by_name['radiant_heroes'].message_type = _HERO
_MATCHINFO.fields_by_name['dire_heroes'].message_type = _HERO
DESCRIPTOR.message_types_by_name['Hero'] = _HERO
DESCRIPTOR.message_types_by_name['MatchInfo'] = _MATCHINFO
_sym_Base.RegisterFileDescriptor(DESCRIPTOR)

Hero = _reflection.GeneratedProtocolMessageType('Hero', (_message.Message,), dict(
  DESCRIPTOR = _HERO,
  __module__ = 'match.pb_pb2'
  # @@protoc_insertion_point(class_scope:Hero)
  ))
_sym_Base.RegisterMessage(Hero)

MatchInfo = _reflection.GeneratedProtocolMessageType('MatchInfo', (_message.Message,), dict(
  DESCRIPTOR = _MATCHINFO,
  __module__ = 'match.pb_pb2'
  # @@protoc_insertion_point(class_scope:MatchInfo)
  ))
_sym_Base.RegisterMessage(MatchInfo)


_HERO.fields_by_name['items']._options = None
# @@protoc_insertion_point(module_scope)
