# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dota.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dota.proto',
  package='dota',
  syntax='proto2',
  serialized_pb=_b('\n\ndota.proto\x12\x04\x64ota\"\xbf\x01\n\x0f\x61\x64\x64itional_unit\x12\x10\n\x08unitname\x18\x01 \x02(\t\x12\x0e\n\x06item_0\x18\x02 \x02(\r\x12\x0e\n\x06item_1\x18\x03 \x02(\r\x12\x0e\n\x06item_2\x18\x04 \x02(\r\x12\x0e\n\x06item_3\x18\x05 \x02(\r\x12\x0e\n\x06item_4\x18\x06 \x02(\r\x12\x0e\n\x06item_5\x18\x07 \x02(\r\x12\x12\n\nbackpack_0\x18\x08 \x02(\r\x12\x12\n\nbackpack_1\x18\t \x02(\r\x12\x12\n\nbackpack_2\x18\n \x02(\r\"7\n\x07\x61\x62ility\x12\x0f\n\x07\x61\x62ility\x18\x01 \x02(\r\x12\x0c\n\x04time\x18\x02 \x02(\r\x12\r\n\x05level\x18\x03 \x02(\r\"\x94\x05\n\x06player\x12\x12\n\naccount_id\x18\x01 \x02(\x04\x12\x13\n\x0bplayer_slot\x18\x02 \x02(\r\x12\x0f\n\x07hero_id\x18\x03 \x02(\r\x12\x0e\n\x06item_0\x18\x04 \x02(\r\x12\x0e\n\x06item_1\x18\x05 \x02(\r\x12\x0e\n\x06item_2\x18\x06 \x02(\r\x12\x0e\n\x06item_3\x18\x07 \x02(\r\x12\x0e\n\x06item_4\x18\x08 \x02(\r\x12\x0e\n\x06item_5\x18\t \x02(\r\x12\x12\n\nbackpack_0\x18\n \x02(\r\x12\x12\n\nbackpack_1\x18\x0b \x02(\r\x12\x12\n\nbackpack_2\x18\x0c \x02(\r\x12\r\n\x05kills\x18\r \x02(\r\x12\x0e\n\x06\x64\x65\x61ths\x18\x0e \x02(\r\x12\x0f\n\x07\x61ssists\x18\x0f \x02(\r\x12\x15\n\rleaver_status\x18\x10 \x02(\r\x12\x11\n\tlast_hits\x18\x11 \x02(\r\x12\x0e\n\x06\x64\x65nies\x18\x12 \x02(\r\x12\x14\n\x0cgold_per_min\x18\x13 \x02(\r\x12\x12\n\nxp_per_min\x18\x14 \x02(\r\x12\r\n\x05level\x18\x15 \x02(\r\x12\x13\n\x0bhero_damage\x18\x16 \x02(\r\x12\x14\n\x0ctower_damage\x18\x17 \x02(\r\x12\x14\n\x0chero_healing\x18\x18 \x02(\r\x12\x0c\n\x04gold\x18\x19 \x02(\r\x12\x12\n\ngold_spent\x18\x1a \x02(\r\x12\x1a\n\x12scaled_hero_damage\x18\x1b \x02(\r\x12\x1b\n\x13scaled_tower_damage\x18\x1c \x02(\r\x12\x1b\n\x13scaled_hero_healing\x18\x1d \x02(\r\x12\'\n\x10\x61\x62ility_upgrades\x18\x1e \x03(\x0b\x32\r.dota.ability\x12/\n\x10\x61\x64\x64itional_units\x18\x1f \x03(\x0b\x32\x15.dota.additional_unit\"(\n\x07players\x12\x1d\n\x07players\x18\x01 \x03(\x0b\x32\x0c.dota.player')
)




_ADDITIONAL_UNIT = _descriptor.Descriptor(
  name='additional_unit',
  full_name='dota.additional_unit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unitname', full_name='dota.additional_unit.unitname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_0', full_name='dota.additional_unit.item_0', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_1', full_name='dota.additional_unit.item_1', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_2', full_name='dota.additional_unit.item_2', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_3', full_name='dota.additional_unit.item_3', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_4', full_name='dota.additional_unit.item_4', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_5', full_name='dota.additional_unit.item_5', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backpack_0', full_name='dota.additional_unit.backpack_0', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backpack_1', full_name='dota.additional_unit.backpack_1', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backpack_2', full_name='dota.additional_unit.backpack_2', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=212,
)


_ABILITY = _descriptor.Descriptor(
  name='ability',
  full_name='dota.ability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ability', full_name='dota.ability.ability', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='dota.ability.time', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='dota.ability.level', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=269,
)


_PLAYER = _descriptor.Descriptor(
  name='player',
  full_name='dota.player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='dota.player.account_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_slot', full_name='dota.player.player_slot', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hero_id', full_name='dota.player.hero_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_0', full_name='dota.player.item_0', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_1', full_name='dota.player.item_1', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_2', full_name='dota.player.item_2', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_3', full_name='dota.player.item_3', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_4', full_name='dota.player.item_4', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_5', full_name='dota.player.item_5', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backpack_0', full_name='dota.player.backpack_0', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backpack_1', full_name='dota.player.backpack_1', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backpack_2', full_name='dota.player.backpack_2', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kills', full_name='dota.player.kills', index=12,
      number=13, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deaths', full_name='dota.player.deaths', index=13,
      number=14, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assists', full_name='dota.player.assists', index=14,
      number=15, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leaver_status', full_name='dota.player.leaver_status', index=15,
      number=16, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_hits', full_name='dota.player.last_hits', index=16,
      number=17, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='denies', full_name='dota.player.denies', index=17,
      number=18, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gold_per_min', full_name='dota.player.gold_per_min', index=18,
      number=19, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xp_per_min', full_name='dota.player.xp_per_min', index=19,
      number=20, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='dota.player.level', index=20,
      number=21, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hero_damage', full_name='dota.player.hero_damage', index=21,
      number=22, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tower_damage', full_name='dota.player.tower_damage', index=22,
      number=23, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hero_healing', full_name='dota.player.hero_healing', index=23,
      number=24, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gold', full_name='dota.player.gold', index=24,
      number=25, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gold_spent', full_name='dota.player.gold_spent', index=25,
      number=26, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scaled_hero_damage', full_name='dota.player.scaled_hero_damage', index=26,
      number=27, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scaled_tower_damage', full_name='dota.player.scaled_tower_damage', index=27,
      number=28, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scaled_hero_healing', full_name='dota.player.scaled_hero_healing', index=28,
      number=29, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ability_upgrades', full_name='dota.player.ability_upgrades', index=29,
      number=30, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additional_units', full_name='dota.player.additional_units', index=30,
      number=31, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=932,
)


_PLAYERS = _descriptor.Descriptor(
  name='players',
  full_name='dota.players',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='players', full_name='dota.players.players', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=934,
  serialized_end=974,
)

_PLAYER.fields_by_name['ability_upgrades'].message_type = _ABILITY
_PLAYER.fields_by_name['additional_units'].message_type = _ADDITIONAL_UNIT
_PLAYERS.fields_by_name['players'].message_type = _PLAYER
DESCRIPTOR.message_types_by_name['additional_unit'] = _ADDITIONAL_UNIT
DESCRIPTOR.message_types_by_name['ability'] = _ABILITY
DESCRIPTOR.message_types_by_name['player'] = _PLAYER
DESCRIPTOR.message_types_by_name['players'] = _PLAYERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

additional_unit = _reflection.GeneratedProtocolMessageType('additional_unit', (_message.Message,), dict(
  DESCRIPTOR = _ADDITIONAL_UNIT,
  __module__ = 'dota_pb2'
  # @@protoc_insertion_point(class_scope:dota.additional_unit)
  ))
_sym_db.RegisterMessage(additional_unit)

ability = _reflection.GeneratedProtocolMessageType('ability', (_message.Message,), dict(
  DESCRIPTOR = _ABILITY,
  __module__ = 'dota_pb2'
  # @@protoc_insertion_point(class_scope:dota.ability)
  ))
_sym_db.RegisterMessage(ability)

player = _reflection.GeneratedProtocolMessageType('player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'dota_pb2'
  # @@protoc_insertion_point(class_scope:dota.player)
  ))
_sym_db.RegisterMessage(player)

players = _reflection.GeneratedProtocolMessageType('players', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERS,
  __module__ = 'dota_pb2'
  # @@protoc_insertion_point(class_scope:dota.players)
  ))
_sym_db.RegisterMessage(players)


# @@protoc_insertion_point(module_scope)
